import React from "react";

import {Inter} from "next/font/google";

import {ReduxProvider} from "@/store/Provider";

import "./globals.css";

import type {Metadata} from "next";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" type="image/svg+xml" href="favicon.svg" />
			</head>
			<body className={inter.className}>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
