name: Next Build

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@3.5.0 --activate

      - name: Install Dependencies
        run: yarn install
        env:
          CI: false
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Build Project
        run: yarn build

      - name: Prepare Build Directory
        run: |
          mkdir -p build
          mv .next build
          cp package.json build/
          cp yarn.lock build/

      - name: Push Build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: {msg}" # The commit message
